. ${srcdir}/emulparams/plt_unwind.sh
SCRIPT_NAME=cgc
OUTPUT_FORMAT="cgc32-i386"
NO_RELA_RELOCS=yes
TEXT_START_ADDR=0x08048000
MAXPAGESIZE="CONSTANT (MAXPAGESIZE)"
ARCH=i386
MACHINE=
TEMPLATE_NAME=cgc32
GENERATE_SHLIB_SCRIPT=yes
CGC_INTERPRETER_NAME=\"/usr/lib/ld.so.1\"
NO_SMALL_DATA=yes
