SCRIPT_NAME=cgc
OUTPUT_FORMAT="cgc32-i386"
NO_RELA_RELOCS=yes
ENTRY=_main
TEXT_BASE=0x0
DYN_TEXT_BASE=0x00400000
TEXT_START_ADDR="(DEFINED(_DYNAMIC) ? ${DYN_TEXT_BASE} : ${TEXT_BASE})"
case ${LD_FLAG} in
    n|N)	TEXT_START_ADDR=0x1000 ;;
esac
MAXPAGESIZE="CONSTANT (MAXPAGESIZE)"
ARCH=i386
MACHINE=
NOP=0x9090
TEMPLATE_NAME=cgc32
GENERATE_SHLIB_SCRIPT=yes
CGC_INTERPRETER_NAME=\"/usr/lib/ld.so.1\"

# Leave room of SIZEOF_HEADERS before text.
EMBEDDED=
